#ifndef LLVM_ANALYSIS_IMMUTABILITY_DEBUG_H
#define LLVM_ANALYSIS_IMMUTABILITY_DEBUG_H

#include <llvm/Support/Debug.h>

#define DEBUG_IMMUTABILITY_ANALYSIS 0
#define DEBUG_FUNCTION_ANALYSIS 0
#define DEBUG_GRAPH 0
#define DEBUG_TRANSFER 0
#define DEBUG_NODE_ALIAS_TRACKER 0

#endif
